### ISSUE TITLE
Add Update Profile option for users.

### ISSUE THREAD

**Issue by diyajaiswal11** [diyajaiswal11/Bloggitt#19] opened 2020-12-02 11:11 UTC
Logged in user should have a update profile option where he can add his profile picture and update his username or email. (Make sure that the username and email is unique even after updating profile.)

- Write templates, views, URLs for the same and also update profile in navbar of home page.

**Comment by Halix267** [comment] 2020-12-02 16:48
@diyajaiswal11 Please assign this to me i want to work on this issue.

**Comment by diyajaiswal11** [comment] 2020-12-02 18:05
> @diyajaiswal11 Please assign this to me i want to work on this issue.

Sure @Halix267 , Go ahead.

**Comment by TrushaT** [comment] 2020-12-07 06:50
please assign this issue to me @diyajaiswal11

**Comment by Halix267** [comment] 2020-12-07 06:58
Hey @TrushaT I am working on this issue.

**Comment by diyajaiswal11** [comment] 2020-12-07 07:00
> Hey @TrushaT I am working on this issue.

Hey @Halix267 , make sure you make a PR within 3 days, or else I'll assign it to @TrushaT

**Comment by Halix267** [comment] 2020-12-07 17:46
@diyajaiswal11 For the update profile option I think we need to show the user profile first. So for that i have raised the issue . Can u assign me that also I will work on both this issue at the same time as for this issue I have to show the user profile first than i will add the update profile section

**Comment by diyajaiswal11** [comment] 2020-12-07 18:51
> @diyajaiswal11 For the update profile option I think we need to show the user profile first. So for that i have raised the issue . Can u assign me that also I will work on both this issue at the same time as for this issue I have to show the user profile first than i will add the update profile section

I don't think there's a need for a separate issue for this. You can work on both the sections under this issue itself.

**Comment by Halix267** [comment] 2020-12-07 18:55
ok but do i can extra points for that as i also have to wrk on #13 issue for this

**Comment by Halix267** [comment] 2020-12-07 18:55
@diyajaiswal11

**Comment by diyajaiswal11** [comment] 2020-12-07 19:43
> ok but do i can extra points for that as i also have to wrk on #13 issue for this

@Halix267 , issue #13 is not related to User Profile. It is an about.html file which displays what the website is about. 
For this issue just read [this](https://github.com/diyajaiswal11/Bloggitt/issues/19#issue-755178784) and push the code accordingly.

**Comment by SubhradeepSS** [comment] 2020-12-08 14:31
@diyajaiswal11 If the issue is not yet solved, can I try to solve it?

**Comment by Halix267** [comment] 2020-12-08 16:22
I solved @SubhradeepSS this issue

**Comment by Halix267** [comment] 2020-12-08 16:23
@diyajaiswal11  Should I style the page or make pr without styling??

**Comment by Halix267** [comment] 2020-12-08 16:33
@diyajaiswal11 Do i style the update profile page or submit it without styling? As I have done all work and ready to make pr, so plzz solve my query?

**Closed** 2020-12-11 12:51 UTC
Labels: intermediate, nwoc
